### ISSUE TITLE
YAMNet Rune fails when using most_confident & label processing blocks

### ISSUE THREAD

**Issue by Mi1ind** [hotg-ai/rune#251]
YAMNet model outputs the confidence array from the model but fails when attempting to use the most_confident & label processing blocks.

**Runefile**
```yaml
version: "1"
image: runicos/base
pipeline:

  audio:
    capability: SOUND
    outputs:
      - type: I16
        dimensions:
          - 1
    args:
      hz: 16000
      sample-duration-ms: 960

  normalize:
    proc-block: "hotg-ai/rune#proc-blocks/audio_float_conversion"
    inputs:
      - audio
    outputs:
      - type: f32
        dimensions:
          - 1

  model:
    model: "./yamnet.tflite"
    inputs:
      - normalize
    outputs:
      - type: F32
        dimensions:
          - 1
          - 521
      - type: F32
        dimensions:
          - 1
          - 1024
      - type: F32
        dimensions:
          - 1
          - 64

  most_confident:
    proc-block: "hotg-ai/rune#proc_blocks/most_confident_indices"
    inputs:
      - model.0
    outputs:
      - type: U32
        dimensions:
          - 1
    args:
      count: 1

  serial:
    out: serial
    inputs:
      - most_confident
```

**Error**
```console
$ rune run yamnet/yamnet.rune --capability=sound:yamnet/assets/up.wav
[2021-08-12T14:14:53.491Z INFO  rune_cli::run] Running rune: yamnet/yamnet.rune
[2021-08-12T14:14:53.690Z DEBUG rune_wasmer_runtime] Loading image
[2021-08-12T14:14:53.690Z DEBUG rune_wasmer_runtime] Instantiating the WebAssembly module
[2021-08-12T14:14:53.731Z DEBUG runicos_base_runtime::image::tf] Loaded model with inputs [TensorInfo { name: "waveform", element_kind: kTfLiteFloat32, dims: [1] }] and outputs [TensorInfo { name: "Identity", element_kind: kTfLiteFloat32, dims: [1, 521] }, TensorInfo { name: "Identity_1", element_kind: kTfLiteFloat32, dims: [1, 1024] }, TensorInfo { name: "Identity_2", element_kind: kTfLiteFloat32, dims: [1, 64] }]
[2021-08-12T14:14:53.731Z DEBUG rune_wasmer_runtime] Loaded the Rune
[2021-08-12T14:14:53.734Z DEBUG rune_wasmer_runtime] Running the rune
[2021-08-12T14:14:53.798Z DEBUG runicos_base_runtime::image] Received message: panicked at 'This proc block only supports 1D inputs', /Users/milind/.cargo/git/checkouts/rune-005ac9981b4d47b5/042abb5/proc-blocks/most_confident_indices/src/lib.rs:35:14
[2021-08-12T14:14:53.800Z WARN  runicos_base_runtime::image] panicked at 'This proc block only supports 1D inputs', /Users/milind/.cargo/git/checkouts/rune-005ac9981b4d47b5/042abb5/proc-blocks/most_confident_indices/src/lib.rs:35:14
Error: Call failed

Caused by:
    0: Unable to call the _call function
    1: RuntimeError: unreachable
           at <unnamed> (<module>[111]:0x80d2)
           at <unnamed> (<module>[224]:0xb429)
           at <unnamed> (<module>[231]:0xbb68)
           at <unnamed> (<module>[31]:0x274c)
           at <unnamed> (<module>[27]:0x1ae5)
           at <unnamed> (<module>[30]:0x25b6)
    2: unreachable
```

**Comment by f0rodo** [comment]
@Michael-F-Bryan  thoughts?

**Comment by f0rodo** [comment]
is this on the test runes yet?

**Comment by Michael-F-Bryan** [comment]
I believe @Mi1ind needs to update the `Runefile.yaml` to this latest version.
