### ISSUE TITLE
Unable to Install `hotg-rune-cli` from Source

### ISSUE THREAD

**Issue by Mi1ind** [hotg-ai/rune#283]
Following the ['Install from Source"](https://hotg.dev/docs/#install-from-source) documentation, downloading the `hotg-rune-cli` from crates.io results in the following error:
```console
$ cargo install hotg-rune-cli

  Updating crates.io index
  Installing hotg-rune-cli v0.6.0
  Downloaded hotg-rune-core v0.6.0
  ...
error: failed to run custom build command for `tflite v0.9.6`

Caused by:
  process didn't exit successfully: `/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-0ad6916900f93b02/build-script-build` (exit status: 101)
  --- stdout
  TARGET = Some("aarch64-apple-darwin")
  HOST = Some("aarch64-apple-darwin")
  CXX_aarch64-apple-darwin = None
  CXX_aarch64_apple_darwin = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_aarch64-apple-darwin = None
  CXXFLAGS_aarch64_apple_darwin = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = None
  running: "c++" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "/Users/milindsaiwaghrey/.cargo/registry/src/github.com-1ecc6299db9ec823/tflite-0.9.6" "-I" "/Users/milindsaiwaghrey/.cargo/registry/src/github.com-1ecc6299db9ec823/tflite-0.9.6/submodules/tensorflow" "-I" "/Users/milindsaiwaghrey/.cargo/registry/src/github.com-1ecc6299db9ec823/tflite-0.9.6/submodules/downloads/flatbuffers/include" "-Wall" "-Wextra" "-fPIC" "-std=c++14" "-Wno-sign-compare" "-DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK" "-DFLATBUFFERS_POLYMORPHIC_NATIVETABLE" "-o" "/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/rust_cpp/cpp_closures.o" "-c" "/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/rust_cpp/cpp_closures.cpp"
  exit status: 0
  AR_aarch64-apple-darwin = None
  AR_aarch64_apple_darwin = None
  HOST_AR = None
  AR = None
  running: "ar" "cq" "/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/librust_cpp_generated.a" "/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/rust_cpp/cpp_closures.o"
  exit status: 0
  running: "ar" "s" "/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/librust_cpp_generated.a"
  exit status: 0
  cargo:rustc-link-lib=static=rust_cpp_generated
  cargo:rustc-link-search=native=/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out
  CXXSTDLIB_aarch64-apple-darwin = None
  CXXSTDLIB_aarch64_apple_darwin = None
  HOST_CXXSTDLIB = None
  CXXSTDLIB = None
  cargo:rustc-link-lib=c++
  Moving tflite source
  Moving source took 474.994875ms
  Building tflite
  cargo:rerun-if-env-changed=TFLITE_RS_MAKE_TARGET
  cargo:rerun-if-env-changed=TFLITE_RS_MAKE_TARGET_ARCH
  cargo:rerun-if-env-changed=TFLITE_RS_MAKE_TARGET_TOOLCHAIN_PREFIX
  cargo:rerun-if-env-changed=TFLITE_RS_MAKE_EXTRA_CFLAGS
  aarch64-linux-gnu-g++ -O3 -DNDEBUG -fPIC  --std=c++11 -march=armv8-a -funsafe-math-optimizations -ftree-vectorize -fPIC -I. -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/../../../../../ -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/../../../../../../ -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/ -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/eigen -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/absl -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I -I/usr/local/include -c tensorflow/lite/allocation.cc -o /private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/gen/aarch64_aarch64/obj/tensorflow/lite/allocation.o
  aarch64-linux-gnu-g++ -O3 -DNDEBUG -fPIC  --std=c++11 -march=armv8-a -funsafe-math-optimizations -ftree-vectorize -fPIC -I. -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/../../../../../ -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/../../../../../../ -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/ -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/eigen -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/absl -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -I/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I -I/usr/local/include -c tensorflow/lite/arena_planner.cc -o /private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/gen/aarch64_aarch64/obj/tensorflow/lite/arena_planner.o

  --- stderr
  make command = "make" "-j" "8" "BUILD_WITH_NNAPI=false" "-f" "tensorflow/lite/tools/make/Makefile" "TARGET=aarch64" "TARGET_ARCH=aarch64" "micro" in dir  "/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow"
  make: aarch64-linux-gnu-g++: No such file or directory
  make: aarch64-linux-gnu-g++: No such file or directory
  make: *** [/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/gen/aarch64_aarch64/obj/tensorflow/lite/allocation.o] Error 1
  make: *** Waiting for unfinished jobs....
  make: *** [/private/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn/release/build/tflite-3c386c8e9a0f47a4/out/tensorflow/tensorflow/lite/tools/make/gen/aarch64_aarch64/obj/tensorflow/lite/arena_planner.o] Error 1
  thread 'main' panicked at 'Failed to build tensorflow', /Users/milindsaiwaghrey/.cargo/registry/src/github.com-1ecc6299db9ec823/tflite-0.9.6/build.rs:146:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `hotg-rune-cli v0.6.0`, intermediate artifacts can be found at `/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installpBG2Sn`

Caused by:
  build failed
```
Installing from Github also results in an error:

```console
$ cargo install --git https://github.com/hotg-ai/rune hotg-rune-cli

    Updating git repository `https://github.com/hotg-ai/rune`
  Installing hotg-rune-cli v0.6.1-dev (https://github.com/hotg-ai/rune#8a2fc872)
    Updating git repository `https://github.com/hotg-ai/serde-yaml`
    Updating git repository `https://github.com/wasm3/wasm3-rs.git`
    Updating crates.io index
    ...
error: failed to run custom build command for `wasm3-sys v0.1.2 (https://github.com/wasm3/wasm3-rs.git?rev=51829c4985fbd7bcc1b52a289f4359617a258589#51829c49)`

Caused by:
  process didn't exit successfully: `/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installg7IdZy/release/build/wasm3-sys-e06360dfa254242c/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to generate bindings: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/milindsaiwaghrey/.cargo/git/checkouts/wasm3-rs-a44766fb80123c43/51829c4/wasm3-sys/build.rs:78:35
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `hotg-rune-cli v0.6.1-dev (https://github.com/hotg-ai/rune#8a2fc872)`, intermediate artifacts can be found at `/var/folders/zw/22pyqybn34s_smdbzh8g80fw0000gn/T/cargo-installg7IdZy`

Caused by:
  build failed
```

**Device Details**
Device: Macbook Pro 
OS: Big Sur (Version 11.2.3)
Achitecture: Apple M1

**Toolchain**
```console
$ rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/milindsaiwaghrey/.rustup

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.54.0 (a178d0322 2021-07-26)
```

**Comment by Michael-F-Bryan** [comment]
@Mi1ind, you need to manually install `bindgen`. This should go away with #259.
